language: java

#avoid bug in : https://github.com/travis-ci/travis-ci/issues/5227
before_install:
  - sudo hostname "$(hostname | cut -c1-63)"

# don't just run the tests, also run Findbugs and friends
script: mvn verify

jdk:
  - oraclejdk7
  - openjdk7

notifications:
  # Email notifications are disabled to not annoy anybody.
  # See http://about.travis-ci.org/docs/user/build-configuration/ to learn more
  # about configuring notification recipients and more.
  email: false
